### ISSUE TITLE
Making the repository public for CI/CD data

### ISSUE THREAD

**Issue by suppathak** [aicoe-aiops/openshift-workload-fingerprinting#47]
As a data scientist, I want to open source the work done in this repo. 

 - [x]  public repository for CI/CD data

**Comment by suppathak** [comment]
https://github.com/aicoe-aiops/openshift-workload-fingerprinting is public for CI/CD data.

**Comment by chauhankaranraj** [comment]
I'm able to see it publicly! :partying_face:
