### ISSUE TITLE
Publish the content of repo as jupyterbook 

### ISSUE THREAD

**Issue by suppathak** [aicoe-aiops/openshift-workload-fingerprinting#48]
As a data scientist, I would like to publish the contents of this repo with meteor as jupyterbook, in order to make the content of this repo more accessible. 

**Acceptance Criteria**
- [x] add toc.yaml and config.yaml 
- [ ] build jupyterbook using meteor
- [ ] build jupyterbook and deploy at gh-pages branch of repo

**Comment by suppathak** [comment]
Here is the link to the jupyterbook: https://aicoe-aiops.github.io/openshift-workload-fingerprinting/ 

It can also be created using https://shower.meteor.zone/ , if we provide the [github repo](https://github.com/aicoe-aiops/openshift-workload-fingerprinting) link. The spawned website creates a jupyterbook.

**Comment by MichaelClifford** [comment]
:partying_face:
